# -*- coding: utf-8 -*-
"""using_openAi keys

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1lEJK4oRB5L-489K_QRC0KOy6jtZV2vMH
"""

!pip install -q openai==1.2.2 tiktoken

import os
from google.colab import userdata

os.environ["OPENAI_API_KEY"] = userdata.get("OPENAI_API_KEY")

from openai import OpenAI
client = OpenAI()

!pip install -q openai==1.2.2 tiktoken
import os
from google.colab import userdata

os.environ["OPENAI_API_KEY"] = userdata.get("OPENAI_API_KEY")


import base64
from openai import OpenAI

client = OpenAI()

# Function to encode the image
def encode_image(image_path):
  with open(image_path, "rb") as image_file:
    return base64.b64encode(image_file.read()).decode('utf-8')

# Path to your image
image_path = "/content/WhatsApp Image 2024-09-09 at 12.00.42 (1).jpeg"

# Getting the base64 string
base64_image = encode_image(image_path)

response = client.chat.completions.create(
  model="gpt-4o-mini",
  messages=[
    {
      "role": "user",
      "content": [
        {
          "type": "text",
          "text": "name of the medicine in json format?",
        },
        {
          "type": "image_url",
          "image_url": {
            "url":  f"data:image/jpeg;base64,{base64_image}"
          },
        },
      ],
    }
  ],
)


print(response.choices[0].message.content)